CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;


CREATE TABLE IF NOT EXISTS bronze.eua_2012 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER
);

CREATE TABLE IF NOT EXISTS bronze.eua_2013 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER
);

CREATE TABLE IF NOT EXISTS bronze.eua_2014 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
);


CREATE TABLE IF NOT EXISTS bronze.eua_2015 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER
);

CREATE TABLE IF NOT EXISTS bronze.eua_2016 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER
);

CREATE TABLE IF NOT EXISTS bronze.eua_2017 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
    average_bid_size REAL,
    average_number_of_bids_per_bidder REAL,
    average_volume_bid_per_bidder REAL,
    average_volume_won_per_bidder REAL,
    number_of_bids_submitted INTEGER,
    number_of_successful_bids INTEGER,
    standard_deviation_of_bid_volume_per_bidder INTEGER,
    standard_deviation_of_volume_won_per_bidde INTEGER,
    austria REAL,
    belgium REAL,
    bulgaria REAL,
    croatia REAL,
    cyprus REAL,
    czech_republic REAL,
    denmark REAL,
    estonia REAL,
    finland REAL,
    france REAL,
    germany REAL,
    greece REAL,
    hungary REAL,
    ireland REAL,
    italy REAL,
    latvia REAL,
    lithuania REAL,
    luxembourg REAL,
    malta REAL,
    netherlands REAL,
    poland REAL,
    portugal REAL,
    romania REAL,
    slovakia REAL,
    slovenia REAL,
    spain REAL,
    sweden REAL
);

CREATE TABLE IF NOT EXISTS bronze.eua_2018 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
    average_bid_size REAL,
    average_number_of_bids_per_bidder REAL,
    average_volume_bid_per_bidder REAL,
    average_volume_won_per_bidder REAL,
    number_of_bids_submitted INTEGER,
    number_of_successful_bids INTEGER,
    standard_deviation_of_bid_volume_per_bidder INTEGER,
    standard_deviation_of_volume_won_per_bidde INTEGER,
    austria REAL,
    belgium REAL,
    bulgaria REAL,
    croatia REAL,
    cyprus REAL,
    czech_republic REAL,
    denmark REAL,
    estonia REAL,
    finland REAL,
    france REAL,
    germany REAL,
    greece REAL,
    hungary REAL,
    ireland REAL,
    italy REAL,
    latvia REAL,
    lithuania REAL,
    luxembourg REAL,
    malta REAL,
    netherlands REAL,
    poland REAL,
    portugal REAL,
    romania REAL,
    slovakia REAL,
    slovenia REAL,
    spain REAL,
    sweden REAL
);


CREATE TABLE IF NOT EXISTS bronze.eua_2019 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
    average_bid_size REAL,
    average_number_of_bids_per_bidder REAL,
    average_volume_bid_per_bidder REAL,
    average_volume_won_per_bidder REAL,
    number_of_bids_submitted INTEGER,
    number_of_successful_bids INTEGER,
    standard_deviation_of_bid_volume_per_bidder INTEGER,
    standard_deviation_of_volume_won_per_bidde INTEGER,
    austria REAL,
    belgium REAL,
    bulgaria REAL,
    croatia REAL,
    cyprus REAL,
    czech_republic REAL,
    denmark REAL,
    estonia REAL,
    finland REAL,
    france REAL,
    germany REAL,
    greece REAL,
    hungary REAL,
    ireland REAL,
    italy REAL,
    latvia REAL,
    lithuania REAL,
    luxembourg REAL,
    malta REAL,
    netherlands REAL,
    poland REAL,
    portugal REAL,
    romania REAL,
    slovakia REAL,
    slovenia REAL,
    spain REAL,
    sweden REAL,
    iceland REAL,
    liechtenstein REAL,
    norway REAL,
    innovation_fund REAL
);


CREATE TABLE IF NOT EXISTS bronze.eua_2020 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
    average_bid_size REAL,
    average_number_of_bids_per_bidder REAL,
    average_volume_bid_per_bidder REAL,
    average_volume_won_per_bidder REAL,
    number_of_bids_submitted INTEGER,
    number_of_successful_bids INTEGER,
    standard_deviation_of_bid_volume_per_bidder INTEGER,
    standard_deviation_of_volume_won_per_bidde INTEGER,
    austria REAL,
    belgium REAL,
    bulgaria REAL,
    croatia REAL,
    cyprus REAL,
    czech_republic REAL,
    denmark REAL,
    estonia REAL,
    finland REAL,
    france REAL,
    germany REAL,
    greece REAL,
    hungary REAL,
    ireland REAL,
    italy REAL,
    latvia REAL,
    lithuania REAL,
    luxembourg REAL,
    malta REAL,
    netherlands REAL,
    poland REAL,
    portugal REAL,
    romania REAL,
    slovakia REAL,
    slovenia REAL,
    spain REAL,
    sweden REAL,
    iceland REAL,
    liechtenstein REAL,
    norway REAL,
    innovation_fund REAL,
    auction_status VARCHAR(15)
);



CREATE TABLE IF NOT EXISTS bronze.eua_2021 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
    average_bid_size REAL,
    average_number_of_bids_per_bidder REAL,
    average_volume_bid_per_bidder REAL,
    average_volume_won_per_bidder REAL,
    number_of_bids_submitted INTEGER,
    number_of_successful_bids INTEGER,
    standard_deviation_of_bid_volume_per_bidder INTEGER,
    standard_deviation_of_volume_won_per_bidde INTEGER,
    austria REAL,
    belgium REAL,
    bulgaria REAL,
    croatia REAL,
    cyprus REAL,
    czech_republic REAL,
    denmark REAL,
    estonia REAL,
    finland REAL,
    france REAL,
    germany REAL,
    greece REAL,
    hungary REAL,
    ireland REAL,
    italy REAL,
    latvia REAL,
    lithuania REAL,
    luxembourg REAL,
    malta REAL,
    netherlands REAL,
    poland REAL,
    portugal REAL,
    romania REAL,
    slovakia REAL,
    slovenia REAL,
    spain REAL,
    sweden REAL,
    iceland REAL,
    liechtenstein REAL,
    norway REAL,
    innovation_fund REAL,
    auction_status VARCHAR(15),
    modernisation_fund REAL
);

CREATE TABLE IF NOT EXISTS bronze.eua_2021 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
    average_bid_size REAL,
    average_number_of_bids_per_bidder REAL,
    average_volume_bid_per_bidder REAL,
    average_volume_won_per_bidder REAL,
    number_of_bids_submitted INTEGER,
    number_of_successful_bids INTEGER,
    standard_deviation_of_bid_volume_per_bidder INTEGER,
    standard_deviation_of_volume_won_per_bidde INTEGER,
    austria REAL,
    belgium REAL,
    bulgaria REAL,
    croatia REAL,
    cyprus REAL,
    czech_republic REAL,
    denmark REAL,
    estonia REAL,
    finland REAL,
    france REAL,
    germany REAL,
    greece REAL,
    hungary REAL,
    ireland REAL,
    italy REAL,
    latvia REAL,
    lithuania REAL,
    luxembourg REAL,
    malta REAL,
    netherlands REAL,
    poland REAL,
    portugal REAL,
    romania REAL,
    slovakia REAL,
    slovenia REAL,
    spain REAL,
    sweden REAL,
    iceland REAL,
    liechtenstein REAL,
    norway REAL,
    innovation_fund REAL,
    auction_status VARCHAR(15),
    modernisation_fund REAL,
    northern_ireland REAL
);

CREATE TABLE IF NOT EXISTS bronze.eua_2022 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
    average_bid_size REAL,
    average_number_of_bids_per_bidder REAL,
    average_volume_bid_per_bidder REAL,
    average_volume_won_per_bidder REAL,
    number_of_bids_submitted INTEGER,
    number_of_successful_bids INTEGER,
    standard_deviation_of_bid_volume_per_bidder INTEGER,
    standard_deviation_of_volume_won_per_bidde INTEGER,
    austria REAL,
    belgium REAL,
    bulgaria REAL,
    croatia REAL,
    cyprus REAL,
    czech_republic REAL,
    denmark REAL,
    estonia REAL,
    finland REAL,
    france REAL,
    germany REAL,
    greece REAL,
    hungary REAL,
    ireland REAL,
    italy REAL,
    latvia REAL,
    lithuania REAL,
    luxembourg REAL,
    malta REAL,
    netherlands REAL,
    poland REAL,
    portugal REAL,
    romania REAL,
    slovakia REAL,
    slovenia REAL,
    spain REAL,
    sweden REAL,
    iceland REAL,
    liechtenstein REAL,
    norway REAL,
    innovation_fund REAL,
    auction_status VARCHAR(15),
    modernisation_fund REAL,
    northern_ireland REAL
);

CREATE TABLE IF NOT EXISTS bronze.eua_2023 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
    average_bid_size REAL,
    average_number_of_bids_per_bidder REAL,
    average_volume_bid_per_bidder REAL,
    average_volume_won_per_bidder REAL,
    number_of_bids_submitted INTEGER,
    number_of_successful_bids INTEGER,
    standard_deviation_of_bid_volume_per_bidder INTEGER,
    standard_deviation_of_volume_won_per_bidde INTEGER,
    austria REAL,
    belgium REAL,
    bulgaria REAL,
    croatia REAL,
    cyprus REAL,
    czech_republic REAL,
    denmark REAL,
    estonia REAL,
    finland REAL,
    france REAL,
    germany REAL,
    greece REAL,
    hungary REAL,
    ireland REAL,
    italy REAL,
    latvia REAL,
    lithuania REAL,
    luxembourg REAL,
    malta REAL,
    netherlands REAL,
    poland REAL,
    portugal REAL,
    romania REAL,
    slovakia REAL,
    slovenia REAL,
    spain REAL,
    sweden REAL,
    iceland REAL,
    liechtenstein REAL,
    norway REAL,
    innovation_fund REAL,
    auction_status VARCHAR(15),
    modernisation_fund REAL,
    northern_ireland REAL,
    inno_fund_rrf REAL,
    ms_rrf REAL
);

CREATE TABLE IF NOT EXISTS bronze.eua_2024 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
    average_bid_size REAL,
    average_number_of_bids_per_bidder REAL,
    average_volume_bid_per_bidder REAL,
    average_volume_won_per_bidder REAL,
    number_of_bids_submitted INTEGER,
    number_of_successful_bids INTEGER,
    standard_deviation_of_bid_volume_per_bidder INTEGER,
    standard_deviation_of_volume_won_per_bidde INTEGER,
    austria REAL,
    belgium REAL,
    bulgaria REAL,
    croatia REAL,
    cyprus REAL,
    czech_republic REAL,
    denmark REAL,
    estonia REAL,
    finland REAL,
    france REAL,
    germany REAL,
    greece REAL,
    hungary REAL,
    ireland REAL,
    italy REAL,
    latvia REAL,
    lithuania REAL,
    luxembourg REAL,
    malta REAL,
    netherlands REAL,
    poland REAL,
    portugal REAL,
    romania REAL,
    slovakia REAL,
    slovenia REAL,
    spain REAL,
    sweden REAL,
    iceland REAL,
    liechtenstein REAL,
    norway REAL,
    innovation_fund REAL,
    auction_status VARCHAR(15),
    modernisation_fund REAL,
    northern_ireland REAL,
    inno_fund_rrf REAL,
    ms_rrf REAL
);


CREATE TABLE IF NOT EXISTS bronze.eua_2025 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
    average_bid_size REAL,
    average_number_of_bids_per_bidder REAL,
    average_volume_bid_per_bidder REAL,
    average_volume_won_per_bidder REAL,
    number_of_bids_submitted INTEGER,
    number_of_successful_bids INTEGER,
    standard_deviation_of_bid_volume_per_bidder INTEGER,
    standard_deviation_of_volume_won_per_bidde INTEGER,
    austria REAL,
    belgium REAL,
    bulgaria REAL,
    croatia REAL,
    cyprus REAL,
    czech_republic REAL,
    denmark REAL,
    estonia REAL,
    finland REAL,
    france REAL,
    germany REAL,
    greece REAL,
    hungary REAL,
    ireland REAL,
    italy REAL,
    latvia REAL,
    lithuania REAL,
    luxembourg REAL,
    malta REAL,
    netherlands REAL,
    poland REAL,
    portugal REAL,
    romania REAL,
    slovakia REAL,
    slovenia REAL,
    spain REAL,
    sweden REAL,
    iceland REAL,
    liechtenstein REAL,
    norway REAL,
    innovation_fund REAL,
    auction_status VARCHAR(15),
    modernisation_fund REAL,
    northern_ireland REAL,
    inno_fund_rrf REAL,
    ms_rrf REAL,
    social_climate_fund REAL
);


CREATE TABLE IF NOT EXISTS bronze.eua_2026 (
    id SERIAL PRIMARY KEY,
    auction_time DATE,
    auction_date DATE NOT NULL,
    contract_type VARCHAR(5)
    eua_price NUMERIC(10, 2) NOT NULL,
    min_eua_price NUMERIC(10, 2),
    max_eua_price NUMERIC(10, 2),
    median_eua_price NUMERIC(10, 2),
    auction_volume INTEGER,
    total_amout_of_bids REAL,
    total_amout_of_bids REAL,
    cover_ratio REAL,
    number_of_bidders REAL,
    number_of_successful_bidders REAL,
    total_revenue REAL,
    country VARCHAR(30) NOT NULL,
    auction_details TEXT,
    auction_year INTEGER,
    auction_month INTEGER,
    auction_day INTEGER,
    average_bid_size REAL,
    average_number_of_bids_per_bidder REAL,
    average_volume_bid_per_bidder REAL,
    average_volume_won_per_bidder REAL,
    number_of_bids_submitted INTEGER,
    number_of_successful_bids INTEGER,
    standard_deviation_of_bid_volume_per_bidder INTEGER,
    standard_deviation_of_volume_won_per_bidde INTEGER,
    austria REAL,
    belgium REAL,
    bulgaria REAL,
    croatia REAL,
    cyprus REAL,
    czech_republic REAL,
    denmark REAL,
    estonia REAL,
    finland REAL,
    france REAL,
    germany REAL,
    greece REAL,
    hungary REAL,
    ireland REAL,
    italy REAL,
    latvia REAL,
    lithuania REAL,
    luxembourg REAL,
    malta REAL,
    netherlands REAL,
    poland REAL,
    portugal REAL,
    romania REAL,
    slovakia REAL,
    slovenia REAL,
    spain REAL,
    sweden REAL,
    iceland REAL,
    liechtenstein REAL,
    norway REAL,
    innovation_fund REAL,
    auction_status VARCHAR(15),
    modernisation_fund REAL,
    northern_ireland REAL,
    inno_fund_rrf REAL,
    ms_rrf REAL,
    social_climate_fund REAL
);